# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14MessageService.proto\x12\x14\x63om.aviasoft.aviabot\".\n\x0eMessageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06themes\x18\x02 \x03(\t\"\x1f\n\x0fMessageResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2d\n\x0eMessageService\x12R\n\x03\x61sk\x12$.com.aviasoft.aviabot.MessageRequest\x1a%.com.aviasoft.aviabot.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEREQUEST']._serialized_start=46
  _globals['_MESSAGEREQUEST']._serialized_end=92
  _globals['_MESSAGERESPONSE']._serialized_start=94
  _globals['_MESSAGERESPONSE']._serialized_end=125
  _globals['_MESSAGESERVICE']._serialized_start=127
  _globals['_MESSAGESERVICE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
